import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import worker from '../src/worker.mjs';import {hashPassword} from '../src/security.mjs';
const migration=readFileSync(new URL('../migrations/0001_business.sql',import.meta.url),'utf8');
const pass='testing-only-correct-horse-2026';
class D1 {
 constructor(){this.db=new DatabaseSync(':memory:');this.db.exec(migration)}
 prepare(query){const db=this.db;let args=[];const statement={bind(...v){args=v;return statement},async first(){return db.prepare(query).get(...args)||null},async all(){return {results:db.prepare(query).all(...args)}},async run(){const info=db.prepare(query).run(...args);return {success:true,meta:{changes:info.changes}}}};return statement}
 async batch(statements){this.db.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());this.db.exec('COMMIT');return out}catch(e){this.db.exec('ROLLBACK');throw e}}
}
async function setup(){const env={DB:new D1(),LOCAL_TEST:'true',PUBLIC_ORIGIN:'https://production.invalid',ASSETS:{fetch:async()=>new Response('asset')}};const owner=crypto.randomUUID();await env.DB.prepare("INSERT INTO users(id,name,email,password_hash,role) VALUES (?,?,?,?,'owner')").bind(owner,'Owner','owner@example.test',await hashPassword(pass)).run();return env}
async function request(env,path,method='GET',data,cookie='',origin='http://localhost'){const headers={Origin:origin,'CF-Connecting-IP':'192.0.2.10'};if(data)headers['Content-Type']='application/json';if(cookie)headers.Cookie=cookie;return worker.fetch(new Request('http://localhost/api/'+path,{method,headers,body:data?JSON.stringify(data):undefined}),env)}
async function login(env,email='owner@example.test'){const res=await request(env,'auth/login','POST',{email,password:pass});assert.equal(res.status,200,await res.clone().text());return res.headers.get('set-cookie').split(';')[0]}
async function register(env,email){const res=await request(env,'auth/register','POST',{name:email,email,password:pass,consent:true,role:'owner'});assert.equal(res.status,201,await res.clone().text());return {cookie:res.headers.get('set-cookie').split(';')[0],user:(await res.json()).user}}
const lead={name:'Test Customer',email:'guest@example.test',service:'Software',description:'Build an operations application',consent:true};
test('anonymous users cannot read CRM, analytics, accounts or projects',async()=>{const e=await setup();for(const p of ['overview','requests','contacts','projects','tasks','users','audit'])assert.equal((await request(e,p)).status,401)});
test('origin validation rejects cross-origin writes',async()=>{const e=await setup();assert.equal((await request(e,'requests','POST',lead,'','https://attacker.test')).status,403)});
test('registration cannot elevate roles; customer data is isolated',async()=>{const e=await setup(),a=await register(e,'a@example.test'),b=await register(e,'b@example.test');assert.equal(a.user.role,'client');assert.equal((await request(e,'overview','GET',null,a.cookie)).status,403);const created=await request(e,'requests','POST',lead,a.cookie);assert.equal(created.status,201);assert.equal((await(await request(e,'requests','GET',null,a.cookie)).json()).items.length,1);assert.equal((await(await request(e,'requests','GET',null,b.cookie)).json()).items.length,0);assert.equal((await request(e,'users','POST',{name:'Escalation',email:'x@example.test',role:'admin',password:pass},a.cookie)).status,403)});
test('email-matching guest requests never become account-owned',async()=>{const e=await setup();assert.equal((await request(e,'requests','POST',lead)).status,201);const a=await register(e,'guest@example.test');assert.equal((await(await request(e,'requests','GET',null,a.cookie)).json()).items.length,0)});
test('phone or email is accepted, contact and consent are mandatory',async()=>{const e=await setup();assert.equal((await request(e,'requests','POST',{...lead,email:'',phone:'+201012345678'})).status,201);assert.equal((await request(e,'requests','POST',{...lead,email:'',phone:''})).status,400);assert.equal((await request(e,'requests','POST',{...lead,consent:false})).status,400)});
test('CRM update and internal notes are audited and restricted',async()=>{const e=await setup(),owner=await login(e),customer=await register(e,'client@example.test');const created=await(await request(e,'requests','POST',lead,customer.cookie)).json();assert.equal((await request(e,'requests/'+created.id,'PATCH',{status:'Qualified'},owner)).status,200);assert.equal((await request(e,'requests/'+created.id,'PATCH',{status:'Won'},customer.cookie)).status,403);assert.equal((await request(e,'requests/'+created.id+'/notes','POST',{body:'Internal qualification note'},owner)).status,201);assert.equal((await request(e,'requests/'+created.id+'/notes','GET',null,customer.cookie)).status,403);const log=await(await request(e,'audit','GET',null,owner)).json();assert.equal(log.items.length,2)});
test('projects expose only assigned customer projects; tasks stay internal',async()=>{const e=await setup(),owner=await login(e),a=await register(e,'a@example.test'),b=await register(e,'b@example.test');const project=await(await request(e,'projects','POST',{title:'Private project',client_id:a.user.id},owner)).json();assert.equal((await(await request(e,'projects','GET',null,a.cookie)).json()).items.length,1);assert.equal((await(await request(e,'projects','GET',null,b.cookie)).json()).items.length,0);assert.equal((await request(e,'projects/'+project.id,'PATCH',{status:'Completed'},a.cookie)).status,403);const task=await request(e,'tasks','POST',{title:'Prepare architecture',project_id:project.id},owner);assert.equal(task.status,201);assert.equal((await request(e,'tasks','GET',null,a.cookie)).status,403)});
test('disable account revokes existing sessions; owner cannot disable owner',async()=>{const e=await setup(),owner=await login(e),a=await register(e,'client@example.test');assert.equal((await request(e,'users/'+a.user.id,'PATCH',{active:false},owner)).status,200);assert.equal((await(await request(e,'me','GET',null,a.cookie)).json()).user,null);const me=await(await request(e,'me','GET',null,owner)).json();assert.equal((await request(e,'users/'+me.user.id,'PATCH',{active:false},owner)).status,403)});
test('logout invalidates the cookie; cookies are HttpOnly and Secure',async()=>{const e=await setup(),res=await request(e,'auth/login','POST',{email:'owner@example.test',password:pass}),cookie=res.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);assert.match(cookie,/Secure/);assert.match(cookie,/SameSite=Lax/);await request(e,'auth/logout','POST',{},cookie.split(';')[0]);assert.equal((await(await request(e,'me','GET',null,cookie.split(';')[0])).json()).user,null)});
test('analytics are opt-in and count browsers rather than events as visitors',async()=>{const e=await setup(),owner=await login(e),visitor=crypto.randomUUID();await request(e,'events','POST',{event:'page_view',page:'home',visitor,consent:false});let d=await(await request(e,'overview','GET',null,owner)).json();assert.equal(d.totals.tracked_browsers,0);for(let i=0;i<3;i++)await request(e,'events','POST',{event:'page_view',page:'home',visitor,consent:true});d=await(await request(e,'overview','GET',null,owner)).json();assert.equal(d.totals.tracked_browsers,1);assert.equal(d.events[0].count,3)});
test('public request rate limit is persistent and enforced',async()=>{const e=await setup();for(let i=0;i<8;i++)assert.equal((await request(e,'requests','POST',lead)).status,201);assert.equal((await request(e,'requests','POST',lead)).status,429)});
test('SQL parameters safely handle search and text payloads',async()=>{const e=await setup(),owner=await login(e);assert.equal((await request(e,'requests','POST',{...lead,name:"O'Reilly <script>bad()</script>"})).status,201);const r=await request(e,"contacts?q="+encodeURIComponent("' OR 1=1 --"),'GET',null,owner);assert.equal(r.status,200,await r.clone().text());assert.equal((await r.json()).items.length,0)});
test('staff role separation prevents sales creating projects and managers changing leads',async()=>{const e=await setup(),owner=await login(e);for(const role of ['sales','manager'])assert.equal((await request(e,'users','POST',{name:role,email:role+'@example.test',password:pass,role},owner)).status,201);const sales=await login(e,'sales@example.test'),manager=await login(e,'manager@example.test');assert.equal((await request(e,'projects','POST',{title:'No permission'},sales)).status,403);const leadRes=await(await request(e,'requests','POST',lead)).json();assert.equal((await request(e,'requests/'+leadRes.id,'PATCH',{status:'Won'},manager)).status,403)});
