'use client';
import {useEffect,useState} from 'react';
import Image from 'next/image';
import {ArrowRight,ArrowUpRight,Check,ChevronRight,Database,Headphones,Package,Users,Wallet,Workflow,Cloud,ShieldCheck,Code2,BarChart3,Server,MessageCircle} from 'lucide-react';
import {services,options,t,type Lang} from '@/lib/content';
const logo='/assets/neural-logo.png';
const layers=[['Software','البرمجيات'],['AI','الذكاء الاصطناعي'],['Automation','الأتمتة'],['Data','البيانات'],['Cloud','السحابة'],['Infrastructure','البنية التحتية']];
const departments=[['Sales','المبيعات',BarChart3],['Customer service','خدمة العملاء',Headphones],['Inventory','المخزون',Package],['Finance','المالية',Wallet],['HR','الموارد البشرية',Users],['Operations','العمليات',Workflow]] as const;
export function ProductVisual({type,lang}:{type:string,lang:Lang}){
 if(type==='software')return <div className="pv pv-software" aria-label="Example of a connected operations interface"><div className="pv-browser"><div className="pv-top"><i/><i/><i/><span>NEURAL / OPERATIONS</span></div><div className="pv-shell"><aside><b>Overview</b><span>Orders</span><span>Customers</span><span>Inventory</span><span>Reports</span></aside><div className="pv-body"><small>GOOD MORNING</small><strong>{lang==='en'?'Everything in one place.':'كل شيء في مكان واحد.'}</strong><div className="pv-metrics"><div><small>Orders</small><b>Live</b></div><div><small>Inventory</small><b>Synced</b></div><div><small>Support</small><b>Connected</b></div></div><div className="pv-chart"><span style={{height:'45%'}}/><span style={{height:'65%'}}/><span style={{height:'52%'}}/><span style={{height:'74%'}}/><span style={{height:'62%'}}/><span style={{height:'88%'}}/><span style={{height:'76%'}}/><span style={{height:'96%'}}/></div></div></div></div><div className="pv-phone"><div className="pv-phone-notch"/><small>NEURAL / MOBILE</small><b>{lang==='en'?'Your day, in sync.':'يومك، بكل وضوح.'}</b><p>● &nbsp; Orders updated</p><p>● &nbsp; Team notified</p><p>● &nbsp; Report ready</p></div></div>;
 if(type==='ai')return <div className="pv pv-ai" aria-label="Example AI assistant interface"><div className="pv-chat"><div className="pv-chat-head"><span className="pv-avatar">N</span><div><b>Neural Assistant</b><small>Connected to your business</small></div><span className="pv-online"/></div><div className="pv-bubble user">{lang==='en'?'What needs my attention today?':'ما الذي يحتاج انتباهي اليوم؟'}</div><div className="pv-bubble assistant">{lang==='en'?'Three orders need review. I have prepared a summary and notified your team.':'هناك ثلاثة طلبات تحتاج للمراجعة. جهّزت ملخصًا وأبلغت الفريق.'}</div><div className="pv-actions"><span>View summary ↗</span><span>Open orders ↗</span></div><div className="pv-input">{lang==='en'?'Ask a question…':'اسأل عن أي شيء…'} <ArrowUpRight size={17}/></div></div><div className="pv-integration">CRM <span>↔</span> AI <span>↔</span> Operations</div></div>;
 if(type==='automation')return <div className="pv pv-flow" aria-label="Example order automation workflow"><div className="flow-heading">{lang==='en'?'When an order arrives':'عندما يصل طلب جديد'}<span>ACTIVE FLOW</span></div><div className="flow-steps">{[['New order','طلب جديد',Package],['Check stock','فحص المخزون',Database],['Notify team','إبلاغ الفريق',MessageCircle],['Ready to deliver','جاهز للتسليم',Check]].map(([en,ar,Icon],i)=><div className="flow-node" key={String(en)}><span className="flow-icon"><Icon size={19}/></span><small>0{i+1}</small><b>{lang==='en'?en as string:ar as string}</b></div>)}</div><p className="flow-caption">{lang==='en'?'The work moves. Your team stays in control.':'العمل يتحرك تلقائيًا، وفريقك يبقى مسيطرًا.'}</p></div>;
 if(type==='data')return <div className="pv pv-data" aria-label="Example business analytics interface"><div className="data-head"><div><small>BUSINESS OVERVIEW</small><strong>{lang==='en'?'See the whole picture.':'صورة أوضح لأعمالك.'}</strong></div><span>● &nbsp; LIVE DATA</span></div><div className="data-panels"><div><small>Sales</small><div className="spark">▁▃▂▄▃▅▄▇</div><p>↑ Trend visible</p></div><div><small>Orders</small><div className="data-bars">{[35,54,43,62,74,59,85].map((n,i)=><i style={{height:n+'%'}} key={i}/>)}</div><p>Across channels</p></div><div><small>Operations</small><div className="data-ring"><span>●</span></div><p>At a glance</p></div></div></div>;
 if(type==='cloud')return <div className="pv pv-cloud" aria-label="Application deployment architecture"><div className="cloud-stack"><div className="cloud-layer"><Cloud size={24}/><span>Cloud environment</span></div><div className="cloud-layer"><Server size={22}/><span>Application services</span></div><div className="cloud-layer"><Database size={22}/><span>Protected data</span></div></div><div className="cloud-label">DESIGNED TO GROW WITH YOU</div></div>;
 if(type==='infrastructure')return <div className="pv pv-infra" aria-label="Connected technology foundation"><div className="infra-center"><Image src={logo} alt="" width={76} height={76}/></div>{[['Applications','التطبيقات'],['Security','الأمان'],['Networks','الشبكات'],['Storage','التخزين']].map((n,i)=><span className={'infra-node in'+i} key={n[0]}>{lang==='en'?n[0]:n[1]}</span>)}<div className="infra-line l1"/><div className="infra-line l2"/><div className="infra-line l3"/><div className="infra-line l4"/></div>;
 return <div className="pv pv-security"><ShieldCheck size={85}/><span>PROTECT / RECOVER / CONTINUE</span></div>
}
function Capability({lang,index,type,kicker,title,desc,link,dark=false}:{lang:Lang,index:number,type:string,kicker:string,title:string,desc:string,link:string,dark?:boolean}){return <section className={'premium-capability reveal '+(dark?'premium-dark':'')} id={'cap-'+type}><div className={'container premium-cap-grid '+(index%2?'reverse':'')}><div className="premium-copy"><span className="premium-kicker">{String(index+1).padStart(2,'0')} / {kicker}</span><h2>{title}</h2><p>{desc}</p><a href={link} className={'premium-link '+(dark?'light-link':'')}>{t[lang].view} <ArrowUpRight size={17}/></a></div><ProductVisual type={type} lang={lang}/></div></section>}
function NeedFinder({lang}:{lang:Lang}){const [selected,setSelected]=useState(0);return <section className="premium-finder reveal"><div className="container finder-grid"><div><span className="premium-kicker">FIND YOUR WAY FORWARD</span><h2>{t[lang].discover}</h2><p>{lang==='en'?'Choose a goal. See where we can help.':'اختر هدفك واكتشف أين يمكننا مساعدتك.'}</p><div className="finder-choices">{options.map((x,i)=><button key={i} onClick={()=>setSelected(i)} aria-pressed={selected===i}>{x[lang==='en'?0:1]}</button>)}</div></div><div className="finder-result"><small>{lang==='en'?'A PRACTICAL STARTING POINT':'نقطة بداية عملية'}</small><h3>{options[selected][lang==='en'?0:1]}</h3><div className="finder-results">{options[selected][2].map((j,i)=><a href={'/services/'+services[j][0]} key={j}><span>0{i+1}</span>{services[j][lang==='en'?1:2]}<ArrowUpRight size={15}/></a>)}</div><a className="premium-button dark-button" href="/start-project">{t[lang].start} <ArrowRight size={15}/></a></div></div></section>}
export default function PremiumHome({lang}:{lang:Lang}){useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[lang]);return <>
<section className="premium-hero"><div className="container premium-hero-grid"><div className="premium-hero-copy"><span className="premium-kicker">SOFTWARE / AI / AUTOMATION / INFRASTRUCTURE</span><h1>{lang==='en'?<>Technology that<br/>thinks with <em>your business.</em></>:<>تقنية تفكر<br/><em>مع أعمالك.</em></>}</h1><p>{lang==='en'?'We design software, AI systems, automation and digital infrastructure that help businesses operate smarter.':'نصمم البرمجيات وأنظمة الذكاء الاصطناعي والأتمتة والبنية الرقمية لتعمل شركتك بذكاء أكبر.'}</p><div className="premium-actions"><a className="premium-button dark-button" href="#cap-software">{lang==='en'?'Explore our capabilities':'استكشف خدماتنا'} <ArrowRight size={16}/></a><a className="premium-button outline-button" href="/start-project">{t[lang].start}</a></div></div><div className="premium-hero-mark"><div className="mark-halo"/><Image src={logo} alt="Neural Networks approved logo" width={680} height={680} priority/><div className="hero-mark-caption">NEURAL NETWORKS COMPANY <span>EST. 2026</span></div></div></div><div className="premium-scroll">{lang==='en'?'SCROLL TO EXPLORE':'مرّر للاستكشاف'} <span>↓</span></div></section>
<section className="premium-problem reveal" id="problem"><div className="container premium-story-grid"><div><span className="premium-kicker">01 / THE CHALLENGE</span><h2>{lang==='en'?<>One business.<br/><em>Too many</em><br/>disconnected systems.</>:<>شركة واحدة.<br/><em>أنظمة كثيرة</em><br/>لا تتواصل.</>}</h2><p>{lang==='en'?'When teams use tools that do not talk to each other, work slows down and decisions get harder.':'عندما لا تتواصل أدوات العمل، تصبح المهام أبطأ والقرارات أصعب.'}</p></div><div className="department-board">{departments.map(([en,ar,Icon],i)=><div className={'department d'+i} key={en}><span><Icon size={18}/></span>{lang==='en'?en:ar}</div>)}</div></div></section>
<section className="premium-connect reveal"><div className="container"><span className="premium-kicker">02 / THE CONNECTION</span><h2>{lang==='en'?<>Now connect <em>everything.</em></>:<>الآن، اربط <em>كل شيء.</em></>}</h2><p>{lang==='en'?'One clear view. Information moves between your teams and systems.':'رؤية واحدة. والمعلومات تتحرك بين فرقك وأنظمتك.'}</p><div className="connect-board"><div className="connect-core"><Image src={logo} alt="Neural Networks logo" width={125} height={125}/></div>{departments.map(([en,ar,Icon],i)=><div className={'connect-chip c'+i} key={en}><Icon size={17}/>{lang==='en'?en:ar}</div>)}<svg className="connect-lines" viewBox="0 0 1200 420" preserveAspectRatio="none" aria-hidden="true"><path d="M190 95 C385 95 390 195 570 207 M1000 95 C805 95 800 195 630 207 M135 213 H570 M1065 213 H630 M190 330 C385 330 390 230 570 213 M1000 330 C805 330 800 230 630 213"/></svg></div></div></section>
<section className="premium-intelligence reveal"><div className="container premium-cap-grid"><div className="premium-copy"><span className="premium-kicker">03 / THEN ADD INTELLIGENCE</span><h2>{lang==='en'?<>AI that becomes<br/>part of <em>your team.</em></>:<>ذكاء اصطناعي<br/><em>ضمن فريقك.</em></>}</h2><p>{lang==='en'?'Let an assistant answer routine questions, find information and move work forward inside the systems you already use.':'مساعد يجيب على الأسئلة المتكررة، ويجد المعلومات، ويحرّك العمل داخل أنظمتك الحالية.'}</p><a className="premium-link light-link" href="/services/artificial-intelligence">{lang==='en'?'Explore practical AI':'استكشف حلول الذكاء الاصطناعي'} <ArrowUpRight size={17}/></a></div><ProductVisual type="ai" lang={lang}/></div></section>
<div className="premium-services-intro reveal"><div className="container"><span className="premium-kicker">WHAT WE BUILD</span><h2>{lang==='en'?<>One company.<br/>Every layer of technology.</>:<>شركة واحدة.<br/>كل طبقات التقنية.</>}</h2><p>{lang==='en'?'Start with one need. Build an ecosystem over time.':'ابدأ باحتياج واحد، ثم ابنِ منظومة متكاملة مع الوقت.'}</p></div></div>
<Capability lang={lang} index={0} type="software" kicker="SOFTWARE" title={lang==='en'?'Software built around your business.':'برمجيات تُبنى حول عملك.'} desc={lang==='en'?'Web, mobile and enterprise applications that fit your operations.':'تطبيقات ويب وموبايل وأنظمة مؤسسية تناسب طريقة عملك.'} link="/services/software-development"/>
<Capability lang={lang} index={1} type="ai" kicker="ARTIFICIAL INTELLIGENCE" title={lang==='en'?'AI that works inside your business.':'ذكاء اصطناعي يعمل داخل شركتك.'} desc={lang==='en'?'Assistants for support, sales, knowledge and day-to-day work.':'مساعدون لخدمة العملاء والمبيعات والمعرفة والمهام اليومية.'} link="/services/artificial-intelligence"/>
<Capability lang={lang} index={2} type="automation" kicker="AUTOMATION" title={lang==='en'?'Less repetition. More progress.':'مهام متكررة أقل. إنجاز أكثر.'} desc={lang==='en'?'Connect the steps between teams so work moves without constant follow-up.':'اربط خطوات العمل بين فرقك لتتحرك المهام دون متابعة يدوية مستمرة.'} link="/services/intelligent-automation"/>
<Capability lang={lang} index={3} type="data" kicker="DATA & ANALYTICS" title={lang==='en'?'Turn information into decisions.':'حوّل المعلومات إلى قرارات.'} desc={lang==='en'?'Bring your numbers together and see what needs attention.':'اجمع أرقامك في مكان واحد واعرف ما يحتاج إلى انتباهك.'} link="/services/data-analytics" dark/>
<Capability lang={lang} index={4} type="cloud" kicker="CLOUD" title={lang==='en'?'Built to scale.':'بنية تنمو معك.'} desc={lang==='en'?'Secure cloud environments for the systems your business depends on.':'بيئات سحابية آمنة للأنظمة التي يعتمد عليها عملك.'} link="/services/cloud-computing"/>
<Capability lang={lang} index={5} type="infrastructure" kicker="INFRASTRUCTURE" title={lang==='en'?'Technology you can rely on.':'تقنية يمكنك الاعتماد عليها.'} desc={lang==='en'?'Networks, security, recovery and managed systems built as one foundation.':'شبكات وأمان وتعافٍ وإدارة أنظمة تشكل أساسًا واحدًا.'} link="/services/networks-infrastructure"/>
<NeedFinder lang={lang}/>
<section className="premium-process reveal"><div className="container"><span className="premium-kicker">FROM IDEA TO OPERATION</span><h2>{lang==='en'?'A clear path from challenge to impact.':'خطوات واضحة من التحدي إلى التنفيذ.'}</h2><div className="premium-timeline">{(lang==='en'?[['Discover','Understand your business'],['Design','Shape the right solution'],['Build','Develop and connect'],['Deploy','Launch and support']]:[['اكتشاف','نفهم عملك'],['تصميم','نضع الحل المناسب'],['بناء','نطوّر ونربط'],['إطلاق','نبدأ وندعم']]).map(([a,b],i)=><div key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></div>)}</div></div></section>
<section className="premium-projects reveal"><div className="container premium-story-grid"><div><span className="premium-kicker">SELECTED WORK</span><h2>{lang==='en'?'Real work. Clear outcomes.':'أعمال حقيقية. نتائج واضحة.'}</h2><p>{lang==='en'?'Verified project stories will appear here once they are ready to share.':'ستظهر هنا قصص مشاريع موثقة عندما تصبح جاهزة للنشر.'}</p><a className="premium-link" href="/projects">{lang==='en'?'View projects':'تصفح المشاريع'} <ArrowUpRight size={17}/></a></div><div className="project-placeholder"><div className="project-browser"><span/><span/><span/></div><div className="project-placeholder-body"><Code2 size={36}/><strong>CASE STUDIES</strong><small>Coming soon / قريبًا</small></div></div></div></section>
<section className="premium-final reveal"><div className="container"><Image src={logo} alt="Neural Networks logo" width={170} height={170}/><span className="premium-kicker">NEURAL NETWORKS COMPANY</span><h2>{lang==='en'?"Let's build what comes next.":'لنبنِ ما هو قادم.'}</h2><p>{lang==='en'?"Tell us what you want to improve. We'll help you design the right technology.":'أخبرنا بما تريد تحسينه، وسنساعدك في تصميم التقنية المناسبة.'}</p><div className="premium-actions"><a className="premium-button dark-button" href="/start-project">{t[lang].start} <ArrowRight size={16}/></a><a className="premium-button outline-button" href="/contact">{t[lang].talk}</a></div></div></section>
</>}
