export type Lang='en'|'ar';
export const services=[
['software-development','Software Development & Digital Solutions','تطوير البرمجيات والحلول الرقمية','We build the digital systems your business needs.','نبني الأنظمة الرقمية التي يحتاجها عملك.','Websites,Mobile applications,Desktop applications,Backend systems,Databases,APIs,SaaS platforms,Enterprise applications,Custom software,Digital platforms'],
['artificial-intelligence','Artificial Intelligence & Intelligent Technologies','الذكاء الاصطناعي والتقنيات الذكية','We turn AI into practical tools that work inside your business.','نحوّل الذكاء الاصطناعي إلى أدوات عملية تعمل داخل شركتك.','AI agents,Virtual assistants,Chatbots,Generative AI,Natural language processing,Computer vision,Image and video analysis,Knowledge bases,AI customer service,AI sales,Enterprise AI integration'],
['intelligent-automation','Intelligent Automation','الأتمتة الذكية','We automate repetitive work so your team can focus on what matters.','نؤتمت الأعمال المتكررة ليركّز فريقك على ما يهم.','Business process automation,Workflow automation,RPA,AI automation,Customer service automation,Sales automation,Marketing automation,Data automation'],
['enterprise-systems','Enterprise Management Systems','أنظمة إدارة المؤسسات','We connect every department through intelligent business systems.','نربط أقسام شركتك عبر أنظمة أعمال ذكية.','ERP,CRM,HR,Payroll,Attendance,Accounting,Finance,Inventory,Warehousing,POS,Procurement,Supply chain,Project management,Operations'],
['digital-transformation','Digital Transformation','التحول الرقمي','We transform manual processes into connected digital experiences.','نحوّل الإجراءات اليدوية إلى عمليات رقمية مترابطة.','Paperless operations,Process digitization,Workflow redesign,Digital strategy,Digital platforms,Enterprise digitization'],
['data-analytics','Data, Analytics & Business Intelligence','البيانات والتحليلات وذكاء الأعمال','We turn your data into decisions.','نحوّل بياناتك إلى قرارات واضحة.','Data engineering,Analytics,Business intelligence,Dashboards,KPIs,Visualization,Predictive analytics,Data integration'],
['systems-integration','Systems Integration','تكامل الأنظمة','We make your systems communicate with each other.','نجعل أنظمتك تتبادل البيانات وتعمل معًا.','API development,ERP integration,CRM integration,Payment integration,Communication platforms,Legacy integration,Cloud integration,Data synchronization'],
['cloud-computing','Cloud Computing','الحوسبة السحابية','We build secure and scalable cloud environments.','نبني بيئات سحابية آمنة وقابلة للنمو.','Cloud architecture,Infrastructure,Migration,Hosting,Monitoring,Management'],
['devops','DevOps & Software Operations','تشغيل البرمجيات وعمليات التطوير','We move software to production faster and more reliably.','نساعدك على إطلاق البرمجيات وتشغيلها بثبات.','CI/CD,Containers,Testing environments,Deployment,Monitoring,Release management,Infrastructure management'],
['networks-infrastructure','Networks & IT Infrastructure','الشبكات والبنية التحتية','We build the technology foundation your business depends on.','نبني الأساس التقني الذي يعتمد عليه عملك.','Network design,LAN,WAN,Wi-Fi,Servers,Storage,Virtualization,Data centers,Monitoring'],
['backup-recovery','Backup, Disaster Recovery & Continuity','النسخ الاحتياطي والتعافي واستمرارية الأعمال','We help protect your systems and data when things go wrong.','نحمي بياناتك ونساعدك على استعادة العمل عند حدوث مشكلة.','Backup,Database backup,Data recovery,System recovery,Disaster recovery,Business continuity'],
['cybersecurity','Cybersecurity & Information Security','الأمن السيبراني وأمن المعلومات','We protect your digital environment.','نساعدك على حماية أنظمتك وبياناتك.','Infrastructure security,Application security,Vulnerability assessment,Access management,Security monitoring,Server hardening,Data protection'],
['managed-support','Technical Support & Managed Systems','الدعم الفني وإدارة الأنظمة','We keep your technology running.','نحافظ على استقرار تقنيتك واستمرار عملها.','Technical support,Maintenance,Server management,Network management,Monitoring,Managed IT services'],
['consulting','Technology Consulting','الاستشارات التقنية','We help businesses make better technology decisions.','نساعد الشركات على اتخاذ قرارات تقنية أفضل.','IT consulting,AI consulting,Digital transformation,Automation,Data,Cloud,Software architecture,Technical assessments'],
['training','Technology Training','التدريب التقني','We help teams gain the skills to use technology with confidence.','نساعد فرق العمل على اكتساب مهارات تقنية قابلة للتطبيق.','Software development,Artificial intelligence,Automation,Data,Cloud,DevOps,Networks,Enterprise technology'],
['equipment','Technology Solutions & Equipment','الحلول والمعدات التقنية','We set up the equipment and environments your systems need.','نجهّز المعدات والبيئات التقنية التي تحتاجها أنظمتك.','IT equipment,Network equipment,Servers,Storage,Installation,Configuration'],
['research-development','Research & Development','البحث والتطوير','We explore emerging technologies and turn promising ideas into real products.','نختبر التقنيات الجديدة ونحوّل الأفكار الواعدة إلى منتجات.','AI research,Software R&D,Automation R&D,Data research,Prototyping,Digital products']
] as const;
export const industries=[['retail','Retail','التجزئة','Connect stores, inventory and customer service.','ربط المتاجر والمخزون وخدمة العملاء.'],['ecommerce','E-Commerce','التجارة الإلكترونية','Make ordering, fulfillment and support work together.','ربط الطلبات والتجهيز والدعم.'],['logistics','Logistics','الخدمات اللوجستية','Track operations, dispatch and delivery.','متابعة العمليات والتوزيع والتسليم.'],['healthcare','Healthcare','الرعاية الصحية','Improve scheduling, records and service workflows.','تحسين المواعيد والسجلات وإجراءات الخدمة.'],['financial-services','Financial Services','الخدمات المالية','Connect information and simplify controlled workflows.','ربط المعلومات وتبسيط الإجراءات المنضبطة.'],['hospitality','Hospitality','الضيافة','Coordinate bookings, operations and guest service.','تنسيق الحجوزات والعمليات وخدمة الضيوف.'],['real-estate','Real Estate','العقارات','Manage inquiries, properties and follow-up.','إدارة الاستفسارات والعقارات والمتابعة.'],['manufacturing','Manufacturing','التصنيع','See production, stock and purchasing in one place.','جمع الإنتاج والمخزون والمشتريات.'],['education','Education','التعليم','Connect enrollment, learning and administration.','ربط التسجيل والتعلّم والإدارة.'],['professional-services','Professional Services','الخدمات المهنية','Organize projects, clients and delivery.','تنظيم المشاريع والعملاء والتنفيذ.'],['startups','Startups','الشركات الناشئة','Build and scale a focused digital product.','بناء منتج رقمي قابل للنمو.'],['enterprise','Enterprise','المؤسسات الكبرى','Integrate systems across departments.','ربط الأنظمة بين الأقسام.'],['public-sector','Public Sector','القطاع العام','Digitize services and internal processes where appropriate.','رقمنة الخدمات والإجراءات الداخلية بحسب المتطلبات.']] as const;
export const t={en:{home:'Home',about:'About',services:'Services',solutions:'Solutions',industries:'Industries',projects:'Projects',insights:'Insights',contact:'Contact',start:'Start a project',explore:'Explore our world',talk:'Talk to our team',discover:'What does your business need?',recommended:'A starting point for you',view:'Explore service',more:'View all services',industry:'Industries we work with',process:'How we work',contactTitle:"Let's build something intelligent.",send:'Send request',next:'Continue',back:'Back'},ar:{home:'الرئيسية',about:'من نحن',services:'الخدمات',solutions:'الحلول',industries:'القطاعات',projects:'المشاريع',insights:'المقالات',contact:'تواصل معنا',start:'ابدأ مشروعك',explore:'اكتشف عالمنا',talk:'تحدث مع فريقنا',discover:'ماذا يحتاج عملك؟',recommended:'حلول مناسبة كبداية',view:'استكشف الخدمة',more:'كل الخدمات',industry:'القطاعات التي نخدمها',process:'كيف نعمل',contactTitle:'لنبنِ شيئًا ذكيًا معًا.',send:'إرسال الطلب',next:'متابعة',back:'رجوع'}};
export const options=[['Build a Digital Product','بناء منتج رقمي',[0,6,7]],['Automate My Business','أتمتة أعمالي',[2,1,6]],['Use Artificial Intelligence','استخدام الذكاء الاصطناعي',[1,5,2]],['Build an ERP or CRM','بناء ERP أو CRM',[3,6,0]],['Understand My Data','فهم بياناتي',[5,1,6]],['Move to the Cloud','الانتقال للسحابة',[7,8,10]],['Connect My Systems','ربط أنظمتي',[6,3,2]],['Build IT Infrastructure','بناء بنية تقنية',[9,7,15]],['Secure My Business','حماية أعمالي',[11,10,12]],['Improve Existing Systems','تطوير الأنظمة الحالية',[13,8,0]]] as const;
