const root=document.getElementById('app'),editor=document.getElementById('editor'),editorBody=document.getElementById('editor-body');
const API=new URL('../api/',import.meta.url);let user=null,config=null,lang=localStorage.getItem('nn-portal-language')||'ar',section='overview',page=1,contactQuery='',staff=[],projects=[],proof='',widget=null;
const t=(ar,en)=>lang==='ar'?ar:en;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={New:['جديد','New'],Contacted:['تم التواصل','Contacted'],Qualified:['مؤهل','Qualified'],Proposal:['عرض سعر','Proposal'],Won:['تم التعاقد','Won'],Lost:['لم يكتمل','Lost'],Planning:['تخطيط','Planning'],Active:['قيد التنفيذ','Active'],Review:['مراجعة','Review'],Completed:['مكتمل','Completed'],'On hold':['معلّق','On hold'],Todo:['للعمل','Todo'],'In progress':['قيد العمل','In progress'],Done:['منجز','Done'],Low:['منخفضة','Low'],Medium:['متوسطة','Medium'],High:['عالية','High'],owner:['مالك الشركة','Owner'],admin:['مسؤول النظام','System admin'],sales:['المبيعات','Sales'],manager:['مدير مشاريع','Project manager'],client:['عميل','Customer']};
const label=x=>labels[x]?t(...labels[x]):x;
const staffRole=()=>user&&user.role!=='client';const crm=()=>['owner','admin','sales'].includes(user?.role);const work=()=>['owner','admin','manager'].includes(user?.role);
const badge=x=>`<span class="badge">${esc(label(x))}</span>`;
const brand=`<a class="brand" href="../"><img src="../public/assets/neural-logo.png" alt="Neural Networks"><span>NEURAL NETWORKS<small>BUSINESS HUB</small></span></a>`;
function notify(message){const node=document.getElementById('toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),4000);}
async function api(path,method='GET',data){const response=await fetch(new URL(path,API),{method,credentials:'same-origin',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});let result;try{result=await response.json()}catch{throw Error(t('الخدمة غير متاحة حاليًا.','Service is currently unavailable.'))}if(!response.ok){if(response.status===401&&user){user=null;auth()}throw Error(result.error||'Request failed.')}return result;}
function error(node,e){node.textContent=e.message;}
function options(values,value=''){return values.map(v=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(label(v))}</option>`).join('')}
function picker(name,caption,values,value='',required=false){return `<label>${caption}<select name="${name}" ${required?'required':''}>${options(values,value)}</select></label>`}
function field(name,caption,type='text',required=false,value=''){return `<label>${caption}<input name="${name}" type="${type}" ${required?'required':''} value="${esc(value)}" maxlength="${type==='password'?128:254}" ${type==='password'?'minlength="12" autocomplete="new-password"':''}></label>`}
function empty(){return `<div class="empty">${t('لا توجد بيانات حتى الآن. ستظهر هنا عند بدء الاستخدام.','No records yet. Your data will appear here as you use the platform.')}</div>`}
function openEditor(title,html){document.getElementById('editor-title').textContent=title;editorBody.innerHTML=html;editor.showModal();}
document.getElementById('close-editor').onclick=()=>editor.close();
async function bindForm(id,handler){const form=document.getElementById(id);form.onsubmit=async e=>{e.preventDefault();const btn=form.querySelector('button[type=submit]'),err=form.querySelector('.error');btn.disabled=true;err.textContent='';try{await handler(Object.fromEntries(new FormData(form)),form)}catch(e){error(err,e)}finally{btn.disabled=false}}}
function language(){lang=lang==='ar'?'en':'ar';localStorage.setItem('nn-portal-language',lang);document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';user?shell():auth();}
async function captcha(){proof='';widget=null;if(config?.local)return;if(!config?.siteKey)return;const host=document.getElementById('verification');if(!host)return;
 const render=()=>{if(!host.isConnected)return;widget=window.turnstile.render(host,{sitekey:config.siteKey,callback:value=>{proof=value},'expired-callback':()=>{proof=''}})};
 if(window.turnstile){render();return}const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=render;script.onerror=()=>{host.textContent=t('تعذر تحميل التحقق. أعد تحميل الصفحة.','Verification could not load. Reload the page.')};document.head.append(script);
}
function auth(mode='login'){
 root.innerHTML=`<div class="auth-layout"><section class="auth-story">${brand}<h1>${t('أعمالك.<br>في مساحة واحدة.','Your business.<br>One connected space.')}</h1><p>${t('تابع طلباتك ومشاريعك. وفريقنا يدير كل خطوة من أول فكرة إلى التسليم.','Follow your requests and projects, while our team manages every step from idea to delivery.')}</p></section><main class="auth-main"><div class="auth-card"><h2>${t('أهلًا بك','Welcome back')}</h2><p>${t('بوابة العملاء وفريق الشركة','Customer and company workspace')}</p>${!config?`<div class="notice">${t('التسجيل والدخول غير متاحين في النسخة الحالية. يلزم تفعيل خدمة الحسابات أولًا.','Accounts are not available on this version yet. The account service needs to be activated.')}</div>`:''}<div class="auth-tabs"><button id="login-tab" class="${mode==='login'?'active':''}">${t('تسجيل الدخول','Sign in')}</button><button id="register-tab" class="${mode==='register'?'active':''}">${t('حساب عميل جديد','Create customer account')}</button></div><form id="auth-form">${mode==='register'?field('name',t('الاسم','Name'),'text',true)+field('company',t('الشركة','Company'))+field('phone',t('رقم الهاتف','Phone'),'tel'):''}${field('email',t('البريد الإلكتروني','Email'),'email',true)}${field('password',t('كلمة المرور — 12 حرفًا على الأقل','Password — at least 12 characters'),'password',true)}${mode==='register'?`<label class="check"><input name="consent" type="checkbox" required>${t('أوافق على استخدام بياناتي لإنشاء الحساب ومتابعة طلباتي.','I agree to the use of my details to create my account and manage my requests.')}</label>`:''}<div id="verification"></div><p class="error" role="alert"></p><button class="button" type="submit" ${!config?'disabled':''}>${mode==='login'?t('دخول','Sign in'):t('إنشاء الحساب','Create account')}</button></form><p class="privacy">${t('بيانات الحساب والطلبات متاحة فقط لك ولفريق الشركة المخوّل. الاشتراك في التسويق اختياري ومنفصل عن الخدمة.','Account and request data are available to you and authorized company staff. Marketing consent is separate and optional.')}</p><div class="auth-foot"><a href="../">${t('العودة للموقع','Back to website')}</a><button id="language" class="text-button">${lang==='ar'?'English':'العربية'}</button></div></div></main></div>`;
 document.getElementById('login-tab').onclick=()=>auth('login');document.getElementById('register-tab').onclick=()=>auth('register');document.getElementById('language').onclick=language;
 bindForm('auth-form',async(data,form)=>{try{const result=await api('auth/'+mode,'POST',{...data,consent:data.consent==='on',proof});user=result.user;section=user.role==='client'?'requests':'overview';await shell()}finally{if(widget!==null&&window.turnstile)window.turnstile.reset(widget);proof=''}});captcha();
}
const pages={overview:['نظرة عامة','Overview','◈'],requests:['طلبات المشاريع','Project requests','↗'],contacts:['العملاء المحتملون','Contacts','◎'],projects:['المشاريع','Projects','▦'],tasks:['المهام','Tasks','✓'],users:['الحسابات والفريق','Accounts & team','◇'],audit:['سجل التعديلات','Audit log','≡'],integrations:['التكاملات والخطة','Integrations & roadmap','⌁'],account:['حسابي','My account','○']};
async function shell(){
 const allowed=staffRole()?['overview','requests',...(crm()?['contacts']:[]),'projects','tasks','users',...(['owner','admin'].includes(user.role)?['audit']:[]),'integrations','account']:['requests','projects','account'];if(!allowed.includes(section))section=allowed[0];
 root.innerHTML=`<div class="shell"><aside class="sidebar">${brand}<nav class="nav" aria-label="Workspace">${allowed.map(key=>`<button data-section="${key}" class="${section===key?'active':''}"><span class="nav-icon">${pages[key][2]}</span>${t(pages[key][0],pages[key][1])}</button>`).join('')}</nav><div class="sidebar-bottom">${t('مساحة خاصة · وصول حسب الصلاحيات','Private workspace · Role-based access')}<br><br>NEURAL NETWORKS COMPANY</div></aside><div class="workspace"><header class="topbar"><div class="identity"><strong>${esc(user.name)}</strong><small>${esc(label(user.role))}</small></div><div class="top-actions"><button class="button secondary" id="language">${lang==='ar'?'EN':'العربية'}</button><a class="button secondary" href="../">${t('الموقع','Website')}</a><button class="button secondary" id="logout">${t('خروج','Sign out')}</button></div></header><main class="content" id="content"></main></div></div>`;
 document.querySelectorAll('[data-section]').forEach(btn=>btn.onclick=()=>{section=btn.dataset.section;page=1;shell()});document.getElementById('language').onclick=language;document.getElementById('logout').onclick=async()=>{try{await api('auth/logout','POST',{});user=null;auth()}catch(e){notify(e.message)}};
 const node=document.getElementById('content');node.innerHTML='<div class="loading">…</div>';try{await renderPage(node)}catch(e){node.innerHTML=`<p class="error">${esc(e.message)}</p>`}
}
function heading(description='',action=''){return `<div class="page-heading"><div><h1>${t(pages[section][0],pages[section][1])}</h1><p>${description}</p></div>${action}</div>`}
function addButton(caption){return `<button class="button" id="create">＋ ${caption}</button>`}
function table(headers,rows){return rows.length?`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`:empty()}
function paginate(node,count){const div=document.createElement('div');div.className='pagination';div.innerHTML=`<button class="button secondary" id="prev" ${page<=1?'disabled':''}>${t('السابق','Previous')}</button><span>${page}</span><button class="button secondary" id="next" ${count<50?'disabled':''}>${t('التالي','Next')}</button>`;node.append(div);div.querySelector('#prev').onclick=()=>{page--;shell()};div.querySelector('#next').onclick=()=>{page++;shell()}}
function metricList(items){if(!items.length)return empty();const max=Math.max(...items.map(x=>x.count),1);return items.map(x=>`<div class="metric-row"><span>${esc(label(x.status||x.event||x.source))}</span><div class="bar"><span style="width:${x.count/max*100}%"></span></div><strong>${x.count}</strong></div>`).join('')}
async function renderPage(node){
 if(section==='overview'){
  const d=await api('overview'),a=d.totals;const stats=[[t('طلبات المشاريع','Project requests'),a.requests],[t('فرص قيد المتابعة','Open leads'),a.open_leads],[t('حسابات العملاء','Customer accounts'),a.accounts],[t('مشاريع نشطة','Active projects'),a.active_projects],[t('مهام مفتوحة','Open tasks'),a.open_tasks],[t('متصفحات وافقت على القياس','Consenting browsers'),a.tracked_browsers]];
  node.innerHTML=heading(t('صورة واضحة عن المبيعات والتنفيذ وتفاعل الموقع.','A clear view of sales, delivery and website activity.'))+`<div class="stats">${stats.map(([name,value],i)=>`<article class="stat"><span class="stat-label">${name}</span><strong class="stat-value">${value}</strong><small>${i===5?t('آخر 30 يومًا · ليس عدد أشخاص مؤكدًا','Last 30 days · not verified unique people'):t('من البيانات المسجلة','From recorded data')}</small></article>`).join('')}</div><div class="columns"><section class="panel"><h2>${t('مراحل البيع','Sales pipeline')}</h2>${metricList(d.pipeline)}</section><section class="panel"><h2>${t('تفاعل الموقع · آخر 30 يومًا','Website events · last 30 days')}</h2>${metricList(d.events)}</section><section class="panel"><h2>${t('مصادر الطلبات','Request sources')}</h2>${metricList(d.sources)}</section><section class="panel"><h2>${t('كيف تقرأ الأرقام؟','Understanding the numbers')}</h2><p class="muted">${t('الطلبات والحسابات أرقام فعلية. قياس الزيارات اختياري؛ لا يشمل من رفض القياس أو حظره، وقد يستخدم الشخص أكثر من متصفح.','Requests and accounts are actual records. Website analytics is opt-in; visitors who decline or block it are excluded, and one person may use several browsers.')}</p></section></div>`;return;
 }
 if(section==='requests'){
  const {items}=await api('requests?page='+page);node.innerHTML=heading(t('من أول استفسار إلى التعاقد.','From first enquiry to signed work.'),addButton(t('طلب مشروع','Project request')))+table([t('العميل','Customer'),t('الخدمة','Service'),t('التواصل','Contact'),t('الحالة','Stage'),t('التاريخ','Date'),''],items.map(x=>`<tr><td>${esc(x.name)}<small>${esc(x.company)}</small></td><td>${esc(x.service)}</td><td>${esc(x.email||x.phone)}</td><td>${badge(x.status)}</td><td>${esc(x.created_at.slice(0,10))}</td><td><button class="text-button" data-detail="${x.id}">${t('التفاصيل','Details')} ↗</button></td></tr>`));document.getElementById('create').onclick=requestForm;document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>requestDetail(items.find(x=>x.id===b.dataset.detail)));paginate(node,items.length);return;
 }
 if(section==='contacts'){
  node.innerHTML=heading(t('بيانات التواصل المقدمة في الطلبات؛ قد تتكرر جهة الاتصال في أكثر من طلب.','Contact records submitted with requests; the same contact may appear more than once.'))+`<form id="search" class="toolbar"><input name="q" value="${esc(contactQuery)}" placeholder="${t('بحث بالاسم أو البريد أو الشركة','Search name, email or company')}"><button class="button">${t('بحث','Search')}</button></form><div id="contact-results"></div>`;
  const render=async q=>{const {items}=await api('contacts?page='+page+'&q='+encodeURIComponent(q));document.getElementById('contact-results').innerHTML=table([t('الاسم','Name'),t('الشركة','Company'),t('البريد','Email'),t('الهاتف','Phone'),t('المصدر','Source'),t('موافقة التسويق','Marketing consent')],items.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.company)}</td><td>${esc(x.email)}</td><td dir="ltr">${esc(x.phone)}</td><td>${esc(x.source)}</td><td>${x.marketing_opt_in?t('نعم','Yes'):t('لا','No')}</td></tr>`));return items.length};document.getElementById('search').onsubmit=e=>{e.preventDefault();contactQuery=String(new FormData(e.currentTarget).get('q')||'');page=1;shell()};const count=await render(contactQuery);paginate(node,count);return;
 }
 if(section==='projects'){
  const {items}=await api('projects');projects=items;node.innerHTML=heading(t('تابع التنفيذ ومواعيد التسليم.','Track delivery and due dates.'),work()?addButton(t('مشروع جديد','New project')):'')+(items.length?`<div class="cards">${items.map(x=>`<article class="work-card">${badge(x.status)}<h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><p>${esc(x.client_name||'')} · ${esc(x.due_date||t('لم يحدد موعد','No due date'))}</p>${work()?`<select data-project="${x.id}" aria-label="${t('حالة المشروع','Project status')}">${options(['Planning','Active','Review','Completed','On hold'],x.status)}</select>`:''}</article>`).join('')}</div>`:empty());if(work())document.getElementById('create').onclick=projectForm;document.querySelectorAll('[data-project]').forEach(el=>el.onchange=()=>update('projects',el.dataset.project,{status:el.value}));return;
 }
 if(section==='tasks'){
  const {items}=await api('tasks');node.innerHTML=heading(t('وزّع العمل وحدد المسؤول والأولوية.','Assign work, responsibility and priority.'),work()?addButton(t('مهمة جديدة','New task')):'')+`<div class="board">${['Todo','In progress','Done'].map(status=>`<section class="board-column"><h2>${label(status)} · ${items.filter(x=>x.status===status).length}</h2>${items.filter(x=>x.status===status).map(x=>`<article class="work-card">${badge(x.priority)}<h3>${esc(x.title)}</h3><p>${esc(x.project_title||t('مهمة عامة','General task'))}</p><p>${esc(x.assignee_name||t('غير مسندة','Unassigned'))} · ${esc(x.due_date||'')}</p>${work()?`<select data-task="${x.id}" aria-label="${t('حالة المهمة','Task status')}">${options(['Todo','In progress','Done'],x.status)}</select>`:''}</article>`).join('')||empty()}</section>`).join('')}</div>`;if(work())document.getElementById('create').onclick=taskForm;document.querySelectorAll('[data-task]').forEach(el=>el.onchange=()=>update('tasks',el.dataset.task,{status:el.value}));return;
 }
 if(section==='users'){
  const {items}=await api('users');node.innerHTML=heading(t('العملاء وفريق الشركة وصلاحيات الوصول.','Customer and staff accounts and access.'),user.role==='owner'?addButton(t('عضو فريق','Staff member')):'')+table([t('الاسم','Name'),t('البريد','Email'),t('الدور','Role'),t('حالة الحساب','Account status'),''],items.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}<small>${x.email_verified?t('موثق','Verified'):t('غير موثق','Unverified')}</small></td><td>${badge(x.role)}</td><td>${x.active?t('نشط','Active'):t('معطّل','Disabled')}</td><td>${user.role==='owner'&&x.role!=='owner'?`<button class="text-button" data-user="${x.id}" data-active="${x.active?'0':'1'}">${x.active?t('تعطيل','Disable'):t('تفعيل','Enable')}</button>`:''}</td></tr>`));if(user.role==='owner')document.getElementById('create').onclick=staffForm;document.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>update('users',b.dataset.user,{active:b.dataset.active==='1'}));return;
 }
 if(section==='audit'){
  const {items}=await api('audit');node.innerHTML=heading(t('آخر 200 تعديل مسجل.','Latest 200 recorded changes.'))+table([t('المستخدم','Actor'),t('العملية','Action'),t('السجل','Record'),t('الوقت','Time')],items.map(x=>`<tr><td>${esc(x.actor)}</td><td>${esc(x.action)}</td><td>${esc(x.entity_id.slice(0,8))}</td><td>${esc(x.created_at)}</td></tr>`));return;
 }
 if(section==='integrations'){
  node.innerHTML=heading(t('خارطة تطوير واضحة. هذه تكاملات مخططة وليست متصلة بعد.','Development roadmap. These integrations are planned, not connected yet.'))+`<div class="phase"><article>${badge(t('المرحلة الثانية','Phase 2'))}<h3>Meta Inbox · Facebook · Instagram · WhatsApp</h3><p>${t('صندوق محادثات موحّد، إسناد للمندوبين، ربط الرسائل بملف العميل، متابعة زمن الرد، وسجل موافقات الحملات. الربط يتطلب إعداد تطبيق Meta والأرقام والصلاحيات الرسمية.','Unified inbox, agent assignment, messages linked to customers, response-time tracking and campaign consent history. Requires a configured Meta app, business numbers and official permissions.')}</p></article><article><h3>${t('المبيعات والمالية','Sales & finance')}</h3><p>${t('عروض أسعار، عقود، فواتير، دفعات ومصروفات، ثم ربحية كل مشروع وتوقع الإيرادات.','Quotations, contracts, invoices, payments and expenses, followed by project profitability and revenue forecasts.')}</p></article><article><h3>${t('التنفيذ وخدمة العملاء','Delivery & support')}</h3><p>${t('مراحل تسليم، تتبع وقت، اعتماد العميل، مرفقات آمنة، تذاكر دعم، اتفاقيات مستوى الخدمة، وجدولة الصيانة.','Milestones, time tracking, client approvals, secure attachments, support tickets, SLAs and maintenance schedules.')}</p></article><article><h3>${t('الأمان وتشغيل الحسابات','Account operations & security')}</h3><p>${t('توثيق البريد، استعادة كلمة المرور عبر البريد، دعوات الفريق، مصادقة متعددة العوامل، وسياسة الاحتفاظ والحذف والتصدير.','Email verification, email password recovery, staff invitations, MFA, and retention, deletion and export policies.')}</p></article></div>`;return;
 }
 if(section==='account'){
  node.innerHTML=heading()+`<section class="panel" style="max-width:600px"><h2>${esc(user.name)}</h2><p>${esc(user.email)}</p><p class="muted">${t('تغيير كلمة المرور يُخرج الجلسات الأخرى.','Changing your password revokes your other sessions.')}</p><form id="password-form">${field('currentPassword',t('كلمة المرور الحالية','Current password'),'password',true)}${field('password',t('كلمة مرور جديدة','New password'),'password',true)}<p class="error" role="alert"></p><button class="button" type="submit">${t('تحديث كلمة المرور','Update password')}</button></form></section>`;bindForm('password-form',async b=>{await api('auth/password','POST',b);notify(t('تم تحديث كلمة المرور','Password updated'));shell()});
 }
}
async function update(kind,key,changes){try{await api(kind+'/'+key,'PATCH',changes);notify(t('تم الحفظ','Saved'));await shell()}catch(e){notify(e.message);await shell()}}
const formEnd=()=>`<p class="error" role="alert"></p><button class="button" type="submit">${t('حفظ','Save')}</button>`;
function requestForm(){openEditor(t('ابدأ مشروعًا','Start a project'),`<form id="request-form"><div class="form-grid">${field('name',t('الاسم','Name'),'text',true,user.name)}${field('company',t('الشركة','Company'),'text',false,user.company)}${field('email',t('البريد الإلكتروني','Email'),'email',false,user.email)}${field('phone',t('رقم الهاتف','Phone'),'tel',false,user.phone)}${field('country',t('الدولة','Country'))}${picker('service',t('الخدمة','Service'),['Software','AI','Automation','ERP / CRM','Data','Cloud','Infrastructure','Security','Consulting'])}${field('budget',t('الميزانية التقريبية (اختياري)','Estimated budget (optional)'))}<label class="span-all">${t('تفاصيل المشروع','Project details')}<textarea name="description" required maxlength="5000"></textarea></label></div><label class="check"><input type="checkbox" name="consent" required>${t('أوافق على التواصل معي بشأن هذا الطلب.','I agree to be contacted about this request.')}</label><label class="check"><input type="checkbox" name="marketingOptIn">${t('أرغب في استقبال أخبار وعروض الشركة (اختياري).','Send me company news and offers (optional).')}</label>${formEnd()}</form>`);bindForm('request-form',async b=>{await api('requests','POST',{...b,consent:b.consent==='on',marketingOptIn:b.marketingOptIn==='on'});editor.close();notify(t('تم استلام طلبك','Your request was received'));section='requests';page=1;shell()})}
async function requestDetail(row){
 openEditor(t('تفاصيل الطلب','Request details'),`<p><strong>${esc(row.name)}</strong> · ${esc(row.company)}</p><p>${esc(row.email)} · ${esc(row.phone)}</p><p>${badge(row.status)} · ${esc(row.service)} · ${esc(row.budget)}</p><div class="detail">${esc(row.description)}</div><p class="privacy">${t('المرجع','Reference')}: ${esc(row.id)}</p>${crm()?`<form id="lead-update">${picker('status',t('مرحلة البيع','Sales stage'),['New','Contacted','Qualified','Proposal','Won','Lost'],row.status)}<label>${t('المسؤول','Assignee')}<select name="assignee_id" id="lead-assignee"></select></label>${formEnd()}</form><hr><h3>${t('ملاحظات داخلية','Internal notes')}</h3><div id="notes"></div><form id="note-form"><label>${t('إضافة ملاحظة','Add a note')}<textarea name="body" required maxlength="3000"></textarea></label>${formEnd()}</form>`:''}`);
 if(crm()){try{const [notes,users]=await Promise.all([api('requests/'+row.id+'/notes'),api('users')]);document.getElementById('notes').innerHTML=notes.items.map(n=>`<div class="note">${esc(n.body)}<small>${esc(n.author)} · ${esc(n.created_at)}</small></div>`).join('')||empty();document.getElementById('lead-assignee').innerHTML='<option value="">—</option>'+users.items.filter(u=>u.role!=='client'&&u.active).map(u=>`<option value="${u.id}" ${u.id===row.assignee_id?'selected':''}>${esc(u.name)}</option>`).join('');bindForm('lead-update',async b=>{await api('requests/'+row.id,'PATCH',b);editor.close();shell()});bindForm('note-form',async b=>{await api('requests/'+row.id+'/notes','POST',b);editor.close();notify(t('تمت إضافة الملاحظة','Note added'));shell()})}catch(e){notify(e.message)}}
}
async function projectForm(){try{const {items}=await api('users');openEditor(t('مشروع جديد','New project'),`<form id="project-form">${field('title',t('اسم المشروع','Project title'),'text',true)}<label>${t('حساب العميل (اختياري)','Customer account (optional)')}<select name="client_id"><option value="">—</option>${items.filter(x=>x.role==='client'&&x.active).map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.email)}</option>`).join('')}</select></label>${field('due_date',t('موعد التسليم','Due date'),'date')}<label>${t('وصف يظهر للعميل','Description visible to the customer')}<textarea name="description" maxlength="3000"></textarea></label>${formEnd()}</form>`);bindForm('project-form',async b=>{await api('projects','POST',b);editor.close();shell()})}catch(e){notify(e.message)}}
async function taskForm(){try{const [u,p]=await Promise.all([api('users'),api('projects')]);openEditor(t('مهمة جديدة','New task'),`<form id="task-form">${field('title',t('المهمة','Task title'),'text',true)}<div class="form-grid"><label>${t('المشروع','Project')}<select name="project_id"><option value="">—</option>${p.items.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join('')}</select></label><label>${t('المسؤول','Assignee')}<select name="assignee_id"><option value="">—</option>${u.items.filter(x=>x.role!=='client'&&x.active).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label>${picker('priority',t('الأولوية','Priority'),['Low','Medium','High'],'Medium')}${field('due_date',t('تاريخ الاستحقاق','Due date'),'date')}</div>${formEnd()}</form>`);bindForm('task-form',async b=>{await api('tasks','POST',b);editor.close();shell()})}catch(e){notify(e.message)}}
function staffForm(){openEditor(t('عضو فريق جديد','New staff member'),`<form id="staff-form">${field('name',t('الاسم','Name'),'text',true)}${field('email',t('البريد','Email'),'email',true)}${picker('role',t('الدور','Role'),['admin','sales','manager'])}${field('password',t('كلمة مرور أولية قوية','Strong initial password'),'password',true)}<p class="privacy">${t('شارك بيانات الدخول بطريقة آمنة، واطلب من العضو تغيير كلمة المرور من حسابه. لا يتم إرسال بريد آلي حاليًا.','Share access securely and ask the staff member to change their password. Automated email invitations are not enabled yet.')}</p>${formEnd()}</form>`);bindForm('staff-form',async b=>{await api('users','POST',b);editor.close();shell()})}
(async()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';try{config=await api('config');if(!config.available)throw Error('Not configured');const result=await api('me');user=result.user}catch{config=null}if(user){section=user.role==='client'?'requests':'overview';await shell()}else auth()})();
