// Runs on both GitHub Pages and the Worker. No lead is reported as sent without an API acknowledgement.
const API=new URL('../api/',import.meta.url),form=document.getElementById('brief-form'),status=document.getElementById('brief-status');
let connected=false,proof='',widget=null,configuration=null;
const tr=(en,ar)=>document.documentElement.lang==='ar'?ar:en;
const preferenceKey='nn-analytics-consent';let consent=false;try{consent=localStorage.getItem(preferenceKey)==='yes'}catch{}
async function call(path,data){const response=await fetch(new URL(path,API),{method:data?'POST':'GET',credentials:'same-origin',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const result=await response.json();if(!response.ok)throw Error(result.error||'Unable to complete request.');return result;}
async function track(event,page='home'){if(!consent||!connected)return;try{let visitor=localStorage.getItem('nn-visitor');if(!visitor){visitor=crypto.randomUUID();localStorage.setItem('nn-visitor',visitor)}await call('events',{event,page,visitor,consent:true})}catch{/* Analytics must never block the page. */}}
function controls(){const b=form.querySelector('[type=submit]'),note=document.getElementById('delivery-note');b.dataset.en=connected?'Send project request ↗':'Download project brief ↓';b.dataset.ar=connected?'إرسال طلب المشروع ↗':'تحميل ملخص المشروع ↓';b.textContent=tr(b.dataset.en,b.dataset.ar);note.dataset.en=connected?'Your details will be used to respond to this request. Marketing is optional.':'Online submission is not available yet. You can save the brief to your device; it will not be sent.';note.dataset.ar=connected?'نستخدم بياناتك للرد على هذا الطلب. الاشتراك في التسويق اختياري.':'الإرسال غير متاح حاليًا. يمكنك حفظ الملخص على جهازك؛ لن يتم إرساله.';note.textContent=tr(note.dataset.en,note.dataset.ar);document.getElementById('lead-consent-row').hidden=!connected;document.getElementById('lead-consent').required=connected;document.getElementById('marketing-consent-row').hidden=!connected;}
function analyticsNotice(){if(document.getElementById('analytics-notice'))return;const box=document.createElement('aside');box.id='analytics-notice';box.className='analytics-notice';const p=document.createElement('p');p.textContent=tr('Allow anonymous website interaction measurement? We do not record form contents in analytics.','تسمح بقياس تفاعلك مع الموقع دون تسجيل محتوى النماذج ضمن الإحصاءات؟');const yes=document.createElement('button'),no=document.createElement('button');yes.textContent=tr('Allow','سماح');no.textContent=tr('No thanks','لا، شكرًا');for(const b of [yes,no]){b.type='button';b.className='pill light'}yes.onclick=()=>{consent=true;try{localStorage.setItem(preferenceKey,'yes')}catch{}box.remove();track('page_view')};no.onclick=()=>{consent=false;try{localStorage.setItem(preferenceKey,'no');localStorage.removeItem('nn-visitor')}catch{}box.remove()};box.append(p,yes,no);document.body.append(box)}
async function initialize(){try{configuration=await call('config');connected=configuration.available===true}catch{connected=false}controls();if(!connected)return;
 let recorded=false;try{recorded=!!localStorage.getItem(preferenceKey)}catch{}if(!recorded)analyticsNotice();else track('page_view');
 const button=document.createElement('button');button.type='button';button.className='text-link';button.textContent=tr('Analytics preferences','تفضيلات قياس الزيارات');button.onclick=analyticsNotice;document.querySelector('.copyright').append(button);
 if(!configuration.local&&configuration.siteKey){const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=()=>{widget=window.turnstile.render('#lead-verification',{sitekey:configuration.siteKey,callback:token=>{proof=token},'expired-callback':()=>{proof=''}})};document.head.append(script)}
}
form.onsubmit=async e=>{e.preventDefault();status.textContent='';const f=new FormData(form),email=String(f.get('email')||'').trim(),phone=String(f.get('phone')||'').trim();if(!email&&!phone){status.textContent=tr('Add your email or phone number so we can reach you.','اكتب البريد أو رقم الهاتف حتى نتمكن من التواصل معك.');return}const button=form.querySelector('[type=submit]');button.disabled=true;try{
 const data={name:f.get('name'),company:f.get('company'),email,phone,country:f.get('country'),service:f.get('priority'),description:f.get('challenge'),budget:f.get('budget'),website:f.get('website'),consent:f.get('consent')==='on',marketingOptIn:f.get('marketingOptIn')==='on',proof};const q=new URLSearchParams(location.search);data.utmSource=q.get('utm_source')||'';data.utmMedium=q.get('utm_medium')||'';data.utmCampaign=q.get('utm_campaign')||'';
 if(connected){const r=await call('requests',data);status.textContent=tr('Request received. Reference: ','تم استلام طلبك. المرجع: ')+r.id;form.reset();track('project_submit','contact')}
 else{const lines=['NEURAL NETWORKS — PROJECT BRIEF',...['name','company','email','phone','country','service','budget','description'].map(k=>k+': '+(data[k]||'')),'','Not submitted. Saved on your device only.'];const url=URL.createObjectURL(new Blob(['\uFEFF',lines.join('\n')],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='neural-networks-project-brief.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent=tr('Saved to your device. This request has not been sent.','تم الحفظ على جهازك. لم يتم إرسال الطلب.')}
 }catch(error){status.textContent=error.message}finally{button.disabled=false;if(widget!==null&&window.turnstile)window.turnstile.reset(widget);proof=''}};
document.querySelectorAll('[data-project]').forEach(el=>el.addEventListener('click',()=>track('project_start','contact')));document.getElementById('service-tabs').addEventListener('click',e=>{if(e.target.closest('[role=tab]'))track('service_view','services')});document.getElementById('language').addEventListener('click',controls);initialize();
